# -*- coding: utf-8 -*-
"""scrape_files.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1oVTaSw1cI_bqOEBc4u90TVKanU2YMzoE
"""

import xml.etree.ElementTree as ET
import datetime
import time
import sys
from urllib.parse import urlencode
from urllib.request import urlopen
from urllib.error import HTTPError

newURL = '{http://arxiv.org/OAI/arXiv/}'
W3 = '{http://www.w3.org/2005/Atom}'
A9 = '{http://a9.com/-/spec/opensearch/1.1/}'
myBASE = 'http://export.arxiv.org/api/query?'

url = 'http://export.arxiv.org/api/query?search_query=all:network'
response = urlopen(url)
xml = response.read()

root = ET.fromstring(xml)
records = root.findall(W3 + 'entry')

root.tag

print(records)

for record in records:
  meta = record.find(W3 + 'summary')